### PR TITLE
Settings restricting file selection to WebM format

### PR DESCRIPTION
**Pull request by stulees**
- settings HTML updated to include a conditionally shown error message
- controller adding a permanent `$watch` on `url` to manage file format validation
- additional e2e tests

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees I think you've got your e2e test comments backwards - save button should be disabled and form should be invalid. :+1:

**Comment by stulees** [comment]
@donnapep Oops, copy/paste mishap. Corrected and have also added another test that likely should have been included. Review again, thanks!

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
