### PR TITLE
Updated widget-settings-ui-components

### PR DESCRIPTION
**Pull request by rodrigopavezi**
It includes a fix for the enter event issue on file-selector

@donnapep @stulees please review. cheers

### CODE REVIEW

**Comment by donnapep** [comment]
:+1:

**Comment by stulees** [comment]
@rodrigopavezi Do you have a presentation handy?

**Comment by rodrigopavezi** [comment]
@stulees yeap, there you go. https://apps.risevision.com/editor/workspace/d2246f28-3bd5-403e-a829-9212caec241f/?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013 

To check the subscription status you can use this company 189822bb-58f4-4047-9446-68370e99df2d
It is a real user company but we create a presentation check the settings but not save it. On the new editor there is an option Add Widget by URL.	

screen shot 2016-02-04 at 1 41 05 pm

Widget is deployed here
http://s3.amazonaws.com/widget-video-rv-test/stage-0/1.0.0/dist/widget.html
https://s3.amazonaws.com/widget-video-rv-test/stage-0/1.0.0/dist/settings.html

cheers

**Comment by stulees** [comment]
@rodrigopavezi Looks good :+1:

**Pull request merged**
