### PR TITLE
Merge video folder settings [stage-2]

### PR DESCRIPTION
**Pull request by stulees**
- Settings UX revised and using `file-selector`
- Backwards compatibility with pre-merge `url` settings property
- Logging "configuration" event with `event_details` either "custom" or "storage"
- Revised and added test coverage
- No version bump

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks

**Comment by rodrigopavezi** [comment]
@stulees I was commented on trello the only thing I am worried is the size of the modals. Besides that looks good. :+1: cheers

**Comment by stulees** [comment]
@rodrigopavezi @donnapep Please review second last commit, thanks

@mmeiers I had to reapply your css selector to this branch since the layout completely changed. Please review last commit, thanks.

**Comment by donnapep** [comment]
:+1:

**Comment by mmeiers** [comment]
:+1: ok thanks for the heads up

**Comment by rodrigopavezi** [comment]
@stulees looks good :+1:

**Pull request merged**
