### PR TITLE
Upgrade widget-common to receive status code in error message from Rise Cache

### PR DESCRIPTION
**Pull request by stulees**

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks

**Comment by rodrigopavezi** [comment]
@sheadarlison looks good :+1: cheers

**Comment by stulees** [comment]
@rodrigopavezi Assuming you meant me ;)

@rodrigopavezi @donnapep I don't think we need to put this through any Validation, I'm looking to deploy and move to Done. Good with you?

**Comment by rodrigopavezi** [comment]
@stulees sorry! I agree. cheers

**Comment by stulees** [comment]
@rodrigopavezi I decided to validate quickly anyway. I've got a presentation running that points to a 3rd party server file that doesn't exist. I've tried with a couple different urls (different servers), the log is always coming back with "The request failed with status code: 0". It seems in this scenario where it is caught within `onerror` of the request, the status code is not going to be 404. We display the right message in the Widget in this scenario, but do you think we have an issue here in how this will affect our metrics?

**Comment by rodrigopavezi** [comment]
@stulees I am wondering now if that also is the case when using the xhr.addEventListener("loadend"..., which was implemented before. I think we were getting the 404 before. Would it be worth to try that out? cheers

**Comment by stulees** [comment]
@rodrigopavezi Yeah I'm going to try that now. 

Another thing to note also is when this runs in preview (rise cache not running), JWPlayer makes the request directly and we end up logging the player error "video - Error loading media: File could not be played" and show a totally different message on the Widget "There was a problem playing that video. It could be that we don't support that format or it is not encoded correctly." I don't see a way around this.

**Comment by rodrigopavezi** [comment]
@stulees this is a known issue where we let these errors to pass because we cannot differentiate from the cross domain issue where it comes with a status 0 error but plays fine on the player. This issue should be solved with the implementation of the proxy service for checking the url. Hopefully we get to implement it soon. cheers

**Pull request merged**
