### PR TITLE
Transpile JS using Babel

### PR DESCRIPTION
**Pull request by donnapep**
- Eliminate `source` task.
- CSS is handled by new `css` task.
- JS is handled by running `js` and then `babel`. `js` copies the files to a `temp` folder and then `babel` reads the files from `temp`, transpiles to ES6 (and minifies and creates source maps for Production) and copies to `dist` folder.
- Source maps are no longer inline and instead are stored in external files to reduce the size of the minified JS.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review again. Underscore.js did not like being put through Babel, so I had to link it out separately.

To be fair, only the Widget-specific code should really be transpiled here, but I started going down a rabbit hole trying to get it to work with `gulp-usemin`. ES6 modules would definitely be a better solution than `gulp-usemin`.

**Comment by stulees** [comment]
@donnapep The build is failing from this latest change. I think it has to do with the prod tasks check.

**Comment by donnapep** [comment]
@stulees It's fixed now. Thx.

**Comment by donnapep** [comment]
@stulees Will this one be good to go once validated? Or do you think we should bump the version in this PR to go out with latest VideoJS stuff?

**Comment by stulees** [comment]
@donnapep Looks good but I do think the version should be bumped to 2.0.0 to go out with our VideoJS epic.

**Comment by donnapep** [comment]
@stulees I rebased against master to pick up the version number change. I've also upgraded `widget-tester`. You can pull down this branch now and try it out if you like to see what happens with the tests, and then review. Thx.

**Comment by stulees** [comment]
@donnapep Checked out your branch, fresh npm install, built and ran the tests. All good 👍

**Comment by donnapep** [comment]
@stulees Sweet, thx!

**Pull request merged**
