### PR TITLE
Upgraded to a new version of the storage component

### PR DESCRIPTION
**Pull request by rodrigopavezi**
Changed the rise-storage-no-file and rise-storage-no-folder
event listeners to log event details
Added a event listener for the rise-cache-error
Fixed tests

@donnapep @stulees please review. cheers

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi There are two separate modules `storage-file.js` and `storage-folder.js` to which `storage-folder.js` already listens for the "rise-storage-no-folder" event. Can you clarify why you're adding it to storage-file? The event won't ever fire when rise-storage is handling a single file. 

Also, can there be a potential "rise-cache-error" occurrence when rise-storage is managing a folder? If so, the event should be listened for in both storage-file and storage folder modules. Thanks

**Comment by rodrigopavezi** [comment]
@stulees sorry, I totally missed the storage-folder. I will make the change. cheers

**Comment by rodrigopavezi** [comment]
@stulees changes made, please review. cheers

**Comment by stulees** [comment]
@rodrigopavezi Changes look good, I think you're duplicating some tests though in the integration test `storage-folder.html`. Have a look to the other integration tests in `logging-storage-folder.html` and `messaging-storage-folder.html`. They have tests pertaining to when there's a storage error.

**Comment by rodrigopavezi** [comment]
@stulees good point, I leveraged those test and added the new ones. Please review. cheers

**Comment by stulees** [comment]
@rodrigopavezi I'm still seeing your tests in `storage-folder.js` and `storage-file.js`. Since your assertions involve logging and showing messages, I think your tests either already exist or are better suited for being in `logging-storage-folder.js`, `logging-storage-file.js`, `messaging-storage-folder.js` and `messaging-storage-file.js`. Thanks

**Comment by rodrigopavezi** [comment]
@stulees storage-folder.js should be reverted now. I think I can leave the extra test on the storage-file as there are others already there. cheers

**Comment by stulees** [comment]
@rodrigopavezi Tests look good now but I think you need to run a build again and push the dist/ files. I'm seeing the "rise-storage-no-folder" event handler in `storage-file` module of the dist `widget.js`.

**Comment by rodrigopavezi** [comment]
@stulees sorry, I keep forgetting the dist folder. I just built it. cheers

**Comment by stulees** [comment]
@rodrigopavezi Looks good :+1:

**Comment by rodrigopavezi** [comment]
@stulees thanks, I will merge it on Monday as a precaution.

**Comment by rodrigopavezi** [comment]
@stulees I added the storage selector version 1.0.1 to bower. Please review. cheers

**Comment by stulees** [comment]
@rodrigopavezi cheers :+1:

**Pull request merged**
