### PR TITLE
Show message on player error

### PR DESCRIPTION
**Pull request by donnapep**
* On a player error, show the JW Player error message on-screen for 5 seconds before sending `done`. If JW Player does not specify error details, show the message "An error occurred with the media player." instead.
* Remove logging.
* Always build a Production version.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. This is the first of the Video PRs that should be deployed. Thx.

**Comment by stulees** [comment]
@donnapep regarding the `circle.yml` change, did we decide to not build a version that will work on rva-test anymore then? Are we only validating/testing on production?

**Comment by donnapep** [comment]
@stulees I don't see the need to build a test version. Alan validates on Production and it's better if we do the same. Building a test version by default just creates more work for us because a separate Production version then needs to be created. This is overhead that we can eliminate from our workflow.

**Comment by stulees** [comment]
@donnapep Agreed :+1:  The only time I see us needing to validate on rva-test is to validate a change to a Widget that is to support a change to Storage, before the change to Storage has been deployed. This doesn't happen often at all though.

**Pull request merged**
