### PR TITLE
Change message for no playable sources [stage-4]

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by rodrigopavezi** [comment]
@donnapep looks good, I just think we don't need to check for youtube anymore. @stulees made a comment about that but I can't remember the reason. Could you remind us your points @stulees? cheers

**Comment by stulees** [comment]
@donnapep @rodrigopavezi In our discussions on Friday, it seems unnecessary in detecting for a youtube URL since we are not displaying a Youtube specific message on the Widget. Also, as far as it went in reviewing past logs, the `PLAYER_ERROR` value was only reported when the format was wrong (eg. mov, swf, etc), so I think we just need to show the `FORMAT_MESSAGE` in this scenario. Thanks

**Comment by donnapep** [comment]
@rodrigopavezi @stulees Please review latest commit. Thx.

**Comment by donnapep** [comment]
Also, @stulees do you have a sample video that you know generates this error? Thx.

**Comment by donnapep** [comment]
@stulees Never mind. Apparently this error only occurs on CAP player, not on Windows native.

**Comment by stulees** [comment]
@donnapep Not off hand, but there are logs that will give you urls to .mov files of users that you could use as a test. Just query for a mov format

**Comment by stulees** [comment]
@donnapep Not sure I follow, it shouldn't matter which player. Which error are you referring to?

**Comment by donnapep** [comment]
@stulees You're right. I restarted the player and it started showing the correct message. Can I consider this PR approved? Thx.

**Comment by stulees** [comment]
@donnapep Yup looks good :+1:

**Comment by rodrigopavezi** [comment]
@donnapep looks good :+1:

**Pull request merged**
