### PR TITLE
Separation of url and rise-storage testing

### PR DESCRIPTION
**Pull request by stulees**
- `gulpfile.js` revised to have two new widget e2e tasks that manually (no use of factory) generate `-e2e` files for url and storage so that they use their own mock data files
- bower update to use latest `widget-settings-ui-components` release
- adding `widget-storage.js` e2e test page with tests set to skip that pertain to the usage of rise-storage
- updated `storage.js` mock data with different values

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review. Note that the two new gulp tasks are forgoing the use of the factory `htmlE2E` function and they generate two different `-e2e` files for testing. It's not the most elegant (I tried to loop instead of having two similar tasks, no luck) but it at least automates the creation of the two `-e2e` HTML files from the main `widget.html`. Thanks

**Comment by donnapep** [comment]
@stulees OK, so this is another step in the right direction, but we still haven't figured out how to test `rise-storage`, is that right?

**Comment by donnapep** [comment]
:+1:

**Comment by stulees** [comment]
@donnapep Yeah, not sure if you saw my Hipchat message in the Widgets room, but it's not working for me when I run the e2e widget server and view it in the browser. I'm not sure how to resolve.

**Pull request merged**
