### PR TITLE
Chore/logging improvements

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. I will rebase after the player error message change ships. Thx.

**Comment by stulees** [comment]
@donnapep Are you in the process of rebasing this branch? Looks like there's conflicts

**Comment by donnapep** [comment]
@stulees Yes, I just deployed the player error, so now I'll rebase.

**Comment by stulees** [comment]
@donnapep Looks good :+1:

**Pull request merged**
