### PR TITLE
Update Storage iframe [stage-4]

### PR DESCRIPTION
**Pull request by ezequielc**
@stulees Please review. 
I will wait for @alanclayton to validate all the widgets before merging. Thanks

### CODE REVIEW

**Comment by alanclayton** [comment]
@ezequielc can you give me the URL's I should be using for review?

**Comment by ezequielc** [comment]
@alanclayton I added all 3 widgets that are being updated to this presentation: http://rva.risevision.com/#/PRESENTATION_MANAGE/id=620bc22e-a2be-40a6-885b-2b0c220eef75?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013
Thanks!

**Comment by stulees** [comment]
@ezequielc :+1:

**Comment by alanclayton** [comment]
@ezequielc Looks good

**Pull request merged**
