### PR TITLE
Change message displayed for a Rise Cache error of any status [stage-2]

### PR DESCRIPTION
**Pull request by stulees**
- Displaying "The video could not be accessed." for a Rise Cache error of any status and for storage and non-storage files
- Adding test coverage

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Assuming the message should be displayed for both storage and non-storage files (confirming with Alan on trello card https://goo.gl/nfXZJH) , please review. Thanks

**Comment by donnapep** [comment]
:+1:

**Comment by stulees** [comment]
@donnapep @rodrigopavezi As per a discussion with @alanclayton , the message has been changed to include Rise Cache in it. Please review last commit, thanks.

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
