### PR TITLE
Only pause video if it's playing

### PR DESCRIPTION
**Pull request by donnapep**
Fix for #76.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by stulees** [comment]
@donnapep :+1: I'm assuming JWPlayer does some internal play/pause toggling if you tell it to pause when it was already paused and this was the source of the issue?

**Comment by donnapep** [comment]
@stulees Yup, that's correct. Thx.

**Comment by donnapep** [comment]
@stulees Given your history of challenges with testing this Widget, do you see any way of testing this change? Thx.

**Comment by stulees** [comment]
@donnapep I don't see a way and it's why I gave the thumbs up without including coverage. We have limitations when it comes to specifics of dealing with video playing via JWPlayer.

**Pull request merged**
