### PR TITLE
Add support for FullStory

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by stulees** [comment]
@donnapep This PR is now overriding the deployed `-test` files from my PR for caching which is already in validation. I'm going to rebuild mine in CCI so it's back again.

**Comment by donnapep** [comment]
@stulees Crap, I should have thought of that.

**Comment by donnapep** [comment]
@stulees How do you want to handle this? Can I add my stuff to your PR?

**Comment by stulees** [comment]
@donnapep Ya probably best to close this PR and add the commit to my PR for caching, thanks.

**Pull request closed without merging**
