### PR TITLE
Enable logging via Player

### PR DESCRIPTION
**Pull request by stulees**

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi Please review last commit. Same deal with this, I think your #192 can be closed for more recent changes on this one. Thanks

**Comment by rodrigopavezi** [comment]
@stulees looks good 👍  cheers

**Comment by stulees** [comment]
@rodrigopavezi Please review last commit, thanks

**Comment by rodrigopavezi** [comment]
@stulees looks good 👍  cheers

**Pull request merged**
