### PR TITLE
Scale to fit and infrastructure for testing undefined values

### PR DESCRIPTION
**Pull request by stulees**
- bower updated to use latest release of `widget-settings-ui-components`
- `video.css` updated to provide two classes to apply depending on scale to fit setting
- `player.js` updated to apply the appropriate class to the `<video>` element for scale to fit or no scale to fit
- e2e tests added for testing scale to fit
- new task added to gulp file "html:e2e:widget:undefined" to build an `-e2e` html file that uses new `undefined.js` mock data
- added `undefined.js` mock data file to use for omitting newly added settings, initially omitting `scaleToFit`
- added `widget-undefined.js` for e2e testing undefined values for newly added settings, initially testing exclusion of `scaleToFit`

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees In `widget-storage.js` the test you added is inside of an `xit`. Is that intentional?
You'll also need to add some tests to ensure that nothing breaks when this setting is missing. You can use [this PR](https://github.com/Rise-Vision/widget-google-calendar/pull/87) for reference. Thx.

**Comment by stulees** [comment]
@donnapep It is set to `xit` because I can't run these tests until we revise the mock for `rise-storage` to allow for multiple instances of `rise-storage` in one HTML page. 

Unfortunately, I also can't use CasperJS in this repo due to PhantomJS not supporting HTML5 media, so I don't know a way that I can dynamically add different mock data. I can verify though that I manually removed the `scaleToFit` setting value from the `url` mock data and tweaked the test to expect `.no-scale` class to be applied and it passed.

**Comment by donnapep** [comment]
@stulees OK, as per the hangout, do you want to update `rise-storage-mock` now or just track it on that card and address it later?

Also, do you know if it's possible to run those tests you have now using Protractor, but also add another gulp task called `test:e2e:undefinedSettings` or similar and use Casper to run just those? So you'd have 3 sets of test that would run -  `test:e2e:settings`, `test:e2e:widget`, and `test:e2e:undefinedSettings`? Just thinking out loud and wondering if something like that would be doable. Thx.

**Comment by stulees** [comment]
@donnapep So I've moved the `rise-storage-mock` card to be my next immediate task after pushing this fix through, so I will address it prior to the next issue #23 fix. Sound okay?

Let me give your suggestion a try regarding `test:e2e:undefinedSettings`, might work out well. Keep you posted, thanks!

**Comment by stulees** [comment]
@donnapep Had to go about this without using CasperJS, but I was able to follow the infrastructure I've already got in place for this repo. Now able to test for `undefined` values for newly added settings and have an initial test for missing `scaleToFit`. Please review again, I'll rebase after.

**Comment by donnapep** [comment]
@stulees Cool! :+1:

**Pull request merged**
