### PR TITLE
Changed the init of the widget to stop flow when legacy player versio…

### PR DESCRIPTION
**Pull request by rodrigopavezi**
…n is found

@stulees @donnapep please review. cheers

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi With this `if/else` block `_ready()` will not get called if legacy is detected, in which case won't this mean Viewer will never show this Widget?

**Comment by rodrigopavezi** [comment]
@stulees alright, do you suggest calling ready anyway? I mean put it outside of the if/else block? cheers

**Comment by stulees** [comment]
@rodrigopavezi The `if/else` is fine, but within the legacy block, I think it should:

```
showError("This version of Video ... ");
_ready();
```

However, I think it also additionally needs a new flag to be used to prevent a refresh from removing this legacy message. Thanks

**Comment by stulees** [comment]
@rodrigopavezi Actually disregard the additional flag, storage won't get created so no concern of a refresh. Thanks

**Comment by rodrigopavezi** [comment]
@stulees makes sense. I made the changes. cheers

**Comment by stulees** [comment]
@rodrigopavezi 👍

**Pull request merged**
