### PR TITLE
Restructure tests and add tests for rise-storage-v2

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by stulees** [comment]
@donnapep So the v2 HTML files set `isV2Running` after importing the JS that include the tests and also overwrite the stub for the widget-common cache `isV2Running()` function in order to ensure rise-storage v2 is applied to the page. Correct?

**Comment by donnapep** [comment]
@stulees That's correct. We could probably go a step further and put the stubs into _v1.js_ and _v2.js_ and import those as well, but at least the test cases are reused.

**Comment by stulees** [comment]
@donnapep 👍 Curious about the whitespace, it caused a build failure?

**Comment by donnapep** [comment]
@stulees When I rebased I didn't remove the `[stage-1]` from the other commit lines so it messed up the deployment part of the build. So I just put in a dummy commit to get it to deploy properly to the correct bucket.

**Comment by stulees** [comment]
@donnapep Ah gotcha 👍

**Pull request merged**
