### PR TITLE
Upgrading to use JWPlayer 7.4.2 [stage-2]

### PR DESCRIPTION
**Pull request by stulees**
**JWPlayer upgrade**
- Targeting jwplayer 7.4.2, self hosted on amazon bucket
- Adhering to latest JWPlayer API
- New custom skin CSS file, based off of JWPlayer "six" skin CSS, replacing skin XML
- Applying necessary CSS overrides for hiding controls and applying existing workarounds
- Removing all logic pertaining to old skin XML
- Player "cache" HTML files updated to add `<link>` to load custom skin CSS
- Removing acceptance of `ogg` and `ogv` files, we only support `webm` and `mp4`
- Unit tests updated

**Version bump and logging version number**
- Feature version bump to `1.1.0`
- gulp "version" task added to create a file with a global var `version` and give it the value of package.json version
- importing `version.js` as part of widget imports to build with
- Using latest widget-common Logger module and logging version number
- unit tests revised
- Integration tests revised to import `version.js`

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks.

Presentation - http://rva.risevision.com/#/PRESENTATION_MANAGE/id=45bb7985-1082-4135-9bf5-5ebb2238f638?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

**Comment by rodrigopavezi** [comment]
@stulees looks good. There is only one thing. BQ is not gathering the tables by the same name with different data time. I think it is because the number on v2. So I guess we have to change it to something else or add an underscore after v2. Thoughts?

screen shot 2016-05-16 at 1 52 22 pm

cheers

**Comment by stulees** [comment]
@rodrigopavezi How about `video_v2_events`?

**Comment by rodrigopavezi** [comment]
@stulees much better. Agreed. cheers

**Comment by stulees** [comment]
@rodrigopavezi Table has been created in BQ and I've revised the table name in the Widget, please review last commit, thanks.

**Comment by rodrigopavezi** [comment]
@stulees looks good 👍 cheers

**Pull request merged**
