### PR TITLE
Executing refresh poll for non-storage video

### PR DESCRIPTION
**Pull request by stulees**
- `player.js` updated to execute a refresh timer to re-load the video with a cache buster, while accounting for all different video state scenarios (playing, paused, paused & at beginning, scrubbing)
- Setup e2e test for non-storage url refresh, but skipping the test because it doesn't seem to work when using sinon fake timers.

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Unfortunately I wasn't successful either on getting e2e tests to pass using Sinon fake timers. I have a test that I have set to skip in `widget-url.js`. In it is a simple example usage of fast forwarding the clock which does work to prove my integration of Sinon fakeTimers is right. Below that, is my real test which doesn't work. Something about the `setTimeout` being in the actual widget code is not coinciding with the use of the fake timer. I can't figure it out and haven't had much luck searching online. Please review, thanks.

**Comment by donnapep** [comment]
@stulees Yeah, I don't get it. And that suggestion in the forum didn't work for me either.
You'll need to build the repo, but everything else looks fine. :+1:

**Comment by stulees** [comment]
@donnapep Built the files, thanks!

**Comment by stulees** [comment]
@donnapep Added the refresh of non-storage background images in this PR. I won't bother rebasing. Please review, thanks

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
