### PR TITLE
Change when configuration event is logged [stage-1]

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by stulees** [comment]
@donnapep An old version of `rise-storage` has been built and added to this PR. I think you need to refresh your local bower components package and rebuild.

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review latest. Thx.

**Comment by stulees** [comment]
@donnapep I see you've updated the way this Widget logs to now be consistent with Image and how we are going to do it moving forward. Will this require an update to Bime for our metrics? 

Also, looks this you need a rebase of master for this branch, there was a deployment of Video today. Thanks

**Comment by donnapep** [comment]
@stulees The same data is still being logged to the same fields as before. I'm just utilizing functionality in `widget-common` now, so no changes to reports.

I've also rebased.

Thx.

**Comment by stulees** [comment]
@donnapep Ok thanks for clarifying :+1:

**Pull request merged**
