### PR TITLE
Updated key

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@donnapep I have updated the jwplayer key, please review. cheers

### CODE REVIEW

**Comment by donnapep** [comment]
:+1:

**Comment by rodrigopavezi** [comment]
@donnapep they are generated files from intelliJ. I usually add those so it doesn't get pushed by mistake.

**Comment by donnapep** [comment]
@rodrigopavezi OK, thanks.

**Comment by rodrigopavezi** [comment]
@donnapep I have changed the cci script so it takes in account the [stage-N] tag on the commit message as to where it should deploy on amazon bucket. Please review. cheers

**Comment by donnapep** [comment]
@rodrigopavezi Awesome! So as we briefly discussed this morning, this will deploy inside the existing test bucket, correct? :+1:

**Comment by rodrigopavezi** [comment]
@donnapep yeap, that is right. The url looks like this http://s3.amazonaws.com/widget-video-rv-test/stage-1/1.0.0/dist/widget.html. cheers

**Comment by rodrigopavezi** [comment]
@donnapep if the tag is missing on the commit message it will default to stage-0. cheers

**Pull request merged**
