### PR TITLE
[Settings] Revisions and Background Image Setting integration

### PR DESCRIPTION
**Pull request by stulees**
- Eliminated unnecessary code in controller due to using latest version of `url-field` component and its `file-type` configuration
- Integrated use of `background-image-setting` in settings HTML and settings app
- e2e tests revised and additional tests added to cover `background-image-setting` component
- bower updated to upgrade release versions of particular dependencies (+1 squashed commit)

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees Ack, I forget to tag the latest release to `rise-storage`. Did that now. The latest is 0.1.3.

**Comment by stulees** [comment]
@donnapep Okay, updated to latest release. Rebased/squashed

**Comment by donnapep** [comment]
@stulees OK, sorry about that. :+1:

**Comment by stulees** [comment]
@donnapep No prob. On the topic of, I've been getting a little caught up recently in versioning/tagging/releases. From `common-style` to `widget-settings-ui-components` to other components ... and then making resolutions for versions, `style-guide`, and then what versions that a widget brings in, etc, etc. Our intentions are good and important for our widgets to point to a particular release, I'm just hoping elsewhere this doesn't get too confusing and tangled to manage ...

**Comment by donnapep** [comment]
@stulees Let's discuss on Thursday.

**Comment by stulees** [comment]
@donnapep Okay sounds good.

**Pull request merged**
