### PR TITLE
Refactoring and optimizing to circumvent memory issues

### PR DESCRIPTION
**Pull request by stulees**
- `player.js` substantially refactored to remove unnecessary listeners, stop storing document fragments, removed a setTimeout, and other improvements
- `video.js` updated to now maintain if its the initial play and also storing if video was previously playing to use later when calling play again
- `video.css` updated as the video container no longer requires being hidden
- updated config files with new test storage modal url values
- ensuring a prod version is being committed to dist/

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep The tests are failing because the `rise-storage-mock` is ahead of this version of `rise-storage`. My next commit to this PR is going to involve upgrading `rise-storage` which will fix the tests. Please review so far, thanks.

**Comment by donnapep** [comment]
@stulees Is this a memory leak then? :+1:

**Comment by stulees** [comment]
@donnapep Short answer yes, narrowing it down. Will need to analyze profiler/timeline again once I get the `rise-storage` upgrade done also. Thanks

**Comment by stulees** [comment]
@donnapep Please review. Note, I was not able to add code for listening to "polymer-ready" because I could not get dispatching the event in my e2e test (protractor, non-angular) to work at all. I have a comment in `main.js` that mentions this and a TODO. I tried a very similar approach as to what we do in Casper but nothing seemed to work in regards to executing the event. I think maintaining the e2e tests are of more value than listening to the `polymer-ready` as this was not causing any issue before without it anyway. If you have any ideas or insight into how I can do it I'm open to suggestions. Thanks

**Comment by donnapep** [comment]
@stulees I think you need to use `polymer-ready`. Part of the problem William was having with his Android player and the Image Folder Widget was that `go` was undefined because the web component hadn't loaded yet. And I myself have seen this before on other players. I'm fixing this in Image Folder now. So `polymer-ready` definitely needs to be there. Thx.

**Comment by stulees** [comment]
@donnapep Have you ever needed to dispatch a window event in protractor and had it work? Any thoughts? Cause if I add the use of `polymer-ready`, I can't seem simulate that event in my e2e tests which leaves me with zero test coverage in storage scenarios.

**Comment by donnapep** [comment]
@stulees Read [this article](http://japhr.blogspot.ca/2014/12/protractor-can-test-polymer-sort-of.html). Might work.

**Comment by stulees** [comment]
@donnapep Not having much luck with this. The combination of trying to e2e test the use of `<video>` and polymer is proving to be a big pita. I'm really not sure how to get around this ...

**Comment by stulees** [comment]
@donnapep Okay, I've done a workaround. Had to include another build expression to include a script for dispatching that event. It's only included for widget-storage-e2e.html. Tests work and all pass now.

**Comment by donnapep** [comment]
@stulees Nice workaround! :+1:

**Pull request closed without merging**
