### PR TITLE
Log 'storage file' or 'storage folder' [stage-1]

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by rodrigopavezi** [comment]
@donnapep looks good :+1: cheers

**Comment by stulees** [comment]
@donnapep :+1:

**Comment by donnapep** [comment]
@rodrigopavezi @stulees All good if I deploy this one straight away?

**Comment by stulees** [comment]
@donnapep I'm good with that

**Comment by rodrigopavezi** [comment]
@donnapep yeap, I am good too. cheers

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Great, thx!

**Pull request merged**
