### PR TITLE
Feature/resume playback

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. Thx.

**Comment by stulees** [comment]
@donnapep Do you have a presentation where I could see the Settings? In looking at the changes, I think elements have been rearranged to be an old UX layout.

**Comment by donnapep** [comment]
@stulees Here's a sample Presentation - http://rva.risevision.com/#/PRESENTATION_MANAGE/id=e347303a-3ed9-4069-9ecd-ab5e03d081a6?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

**Comment by stulees** [comment]
@donnapep The settings should be in this layout order - http://www.screencast.com/t/xmWnPCyRI4GD . It's possible that the last UX prototype wasn't updated to this, but it was definitely discussed and approved by @mmeiers when the Settings work got done for Video. Thanks

**Comment by donnapep** [comment]
@stulees Made the change to destroy the iframe for both files and folders. The verdict is still out on the settings. Thx.

**Comment by stulees** [comment]
@donnapep We went through the changes to Settings in the completed card for merging Folder https://goo.gl/nm1woM. Scroll down to the last messages between Mat and I on Dec 1st, specifically one he says "Sounds good, lets arrange like this: http://www.screencast.com/t/8K31oIBHHD"

re: removing frame, looks good, thanks.

**Comment by donnapep** [comment]
@stulees You're probably right, but I'm still going to wait for confirmation from one of them. I don't know what conversations might have happened since then, and Mat confirmed the prototype link earlier that I built the settings from. I would just hate to change it all and then realize it was right the first time. Thx.

**Comment by mmeiers** [comment]
@donnapep Yes @stulees I correct, it should be ordered like that. He made the change to the widget but I never went back to update the prototype. Sorry for the confusion.

**Comment by donnapep** [comment]
@stulees Settings have been updated in the last commit. Thx!

**Comment by stulees** [comment]
@donnapep One question regarding common-i18n release, otherwise :+1:

**Comment by donnapep** [comment]
@stulees One small tweak as I realized that the setting was not being checked by default if the setting didn't exist yet. Please review. Thx!

**Comment by stulees** [comment]
@donnapep :+1:

**Pull request merged**
