### PR TITLE
[Fixes] JWPlayer context menu / Multiple widget instances

### PR DESCRIPTION
**Pull request by stulees**
- bower updated to force tag dependency for common-style
- settings HTML corrected to point to proper component package for common-style
- Issue # 36 (JWPlayer context menu)
	- `player.html` updated to add new class `.disable-context-menu` which forces display value to none
	- `player.js` updated to apply `.disable-context-menu` to JWPlayer context menu element with id "player_menu"
- Issue # 38 (Multiple instances issue)
	- removed implementation of duplicate frame containers and swapping visibility, etc
	- removed forcing video playback (to test for an error) before widget notifies ready
	- iframe is destroyed when video is complete and is not recreated again until next time widget is told to play
	- setting a black background color on container element to eliminate any visual ugliness when iframe is destroyed
- Overall improvements
	- revised refresh to only set a new value for `currentFile` and allow for another playback attempt if previous playback was an error
	-  changed the non-storage refresh to a repeating interval

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review. This PR fixes issues #36 and #38 . Thanks

**Comment by donnapep** [comment]
@stulees Should `video-revised.js` have been committed?

**Comment by stulees** [comment]
@donnapep No, was a temporary working file. I've now removed, thanks for catching that.

**Comment by donnapep** [comment]
:+1:

**Comment by stulees** [comment]
@donnapep I'm not sure why but my addition of integration tests using WCT are failing on CCI. From what I can decipher I think there is a Chrome version issue, but this is odd because I've not experienced this with web component repos. Also, everything runs fine locally and I've ensured removing node_modules, running npm cache clean, re-installing npm and bower. Otherwise, please review latest commit on this PR, thanks.

**Comment by donnapep** [comment]
@stulees You need to install a later version of Chrome in your `circle.yml` file - https://github.com/Rise-Vision/widget-image/blob/chore/update-rise-storage/circle.yml#L8. They are going to be updating CCI to a newer version of Chrome at the end of the month, so after that we can stop adding this to the file.

I think you'll also need to account for a deleted file?

**Comment by stulees** [comment]
@donnapep Applied the additional Chrome details in `circle.yml`, all good now, thanks. Which deleted file are you referring to?

**Comment by donnapep** [comment]
@stulees I mean if you get a Storage file back that has `file.deleted` set to true.

**Comment by stulees** [comment]
@donnapep Hm, I never really considered that a scenario to happen but I guess it could. How do you think we should handle that? Send the Done event whenever told to play from then on?

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
