### PR TITLE
Applying background image via URL and rise-storage

### PR DESCRIPTION
**Pull request by stulees**
- Widget
	- `main.js` updated to retrieve `companyId` and `additionalParams` and provide them for `RiseVision.Video`
	- `background.js` added to manage the configuration of the document background color and apply a background image if applicable
	- `video.js` added and creates a new instance of `RiseVision.Video.Background`
	- `widget.html` updated to define elements and necessary styles associated with applying a background image and import further source files
- Settings
	- controller updated to `$watch` the background image url so that `backgroundStorage` can be saved if a storage url is applied
- bower updated to use specific release of `widget-settings-ui-core`
- test infrastructure revised with two data files `url.js` and `storage.js` and widget e2e tests added for testing background when a url is used
- gulp file updated to ensure newly named `url.js` is used for e2e tests that pertain to non-storage urls used for video and background image

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Not quite sure I understand what the issue is with the circle ci build failing. Can you take a look? Thanks

**Comment by donnapep** [comment]
@stulees It was still using the old credentials. I must've missed this one. It's working now.

**Comment by stulees** [comment]
@donnapep Okay thanks. 

re: this PR, it pertains to applying a background image in the widget and I've used the same approach as you did in Image Widget for e2e tests. However, I'm not doing anything to test the use of `rise-storage` yet. I took a look at yours and how far you got with it. I'd like to move on and work on the video portion of the widget and come back to figuring something out for testing using `rise-storage`. Please review, thanks

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
