### PR TITLE
Adding support for displaying messages regarding rise-storage events

### PR DESCRIPTION
**Pull request by stulees**
- Updating rise-storage version to 1.1.1
- Displaying a message when `rise-storage` is fetching video file
- Displaying a message when a selected storage file doesn't exist
- Notifying `ready` to Viewer prior to storage init or non-storage video frame loading
- Moving widget css to its own file and building with `message.css` to create a `dist/css/widget.min.css`

### CODE REVIEW

**Comment by stulees** [comment]
@alex-deaconu Please review (last one of these messaging PRs). Thanks!

**Comment by alex-deaconu** [comment]
:+1:

**Comment by stulees** [comment]
@donnapep Please review last commit, thanks

**Comment by donnapep** [comment]
:+1:

**Comment by stulees** [comment]
@donnapep Last commit resolves jquery conflict, can you review so it can be deployed, thanks

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
