### PR TITLE
Widget e2e test revision

### PR DESCRIPTION
**Pull request by stulees**
- bower updated to use new `widget-settings-ui-components` tag release
- applied fix for background over top of video to widget HTML
- updated test data files to do away with `loop` and `autohide` properties
- converted `widget-url.js` test file to use Protractor/selenium instead of CasperJS so that `<video>` can be properly tested as `<video>` is not supported in PhantomJS
- removing `widget-storage.js` e2e test file
- task "test:e2e:widget:run" updated in gulp file to implement e2e angular testing so that Protractor/selenium get used for `widget-url.js` test file

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep So, as mentioned on Hipchat, PhantomJS (used by CasperJS) doesn't support HTML5 media, hence why I couldn't get my e2e tests to work against `<video>`. @alex-deaconu had a good suggestion to use Protractor/selenium as it is possible to use it for a non-Angular page. `widget-url.js` is now converted to do this and it works. The `beforeEach` call on lines 19-23 show how this is possible.

I'm still unsure about testing using `rise-storage` though. I'll look into a possible way to avoid creating multiple HTML files to do so first. I'll work on that next. Thanks

**Comment by donnapep** [comment]
@stulees Do you think we should try to just use Protractor / Selenium for all of our tests and get rid of CasperJS altogether? I personally find it difficult trying to constantly switch gears and figuring out which syntax I need to be using for our different types of tests. :+1:

**Comment by stulees** [comment]
@donnapep I don't know yet at this point. The way I got this to work is by setting `browser.ignoreSynchronization = true`. However, the scope of this flag `ignoreSynchronization` affects the whole suite of test, it’s a global change. It's pretty easy to get around this, this blog post explains well - http://ng-learn.org/2014/02/Protractor_Testing_With_Angular_And_Non_Angular_Sites/

I don't know if we're going to lose some benefits of CasperJS when testing non Angular sites (our actual widgets). What I'm having to do for this Widget is likely to be an exception to all our widgets because of the necessity of `<video>`. However, maybe using Protractor/Selenium is our way to successfully test usage of `rise-storage` and further web components we build. That's yet to be seen.

**Comment by alex-deaconu** [comment]
@stulees nice! :+1:

**Pull request merged**
