### PR TITLE
Hiding frame container until player is ready

### PR DESCRIPTION
**Pull request by stulees**
- To avoid flicker of white from `<iframe>` loading its source, hiding visibility of the frame container div until the player is ready
- Adding specific casperjs version to circle file
- Waiting for rise-storage-response to be fired before running initialization tests
- Adding tests for ensuring proper RiseVision.Video functions are called on initial storage response and when `changed`

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees The code looks good, but I can't actually get it to work on a Player. Do you have a working Presentation that I can try?

**Comment by stulees** [comment]
@donnapep My schedule is here - http://rva-test.appspot.com/#/SCHEDULE_MANAGE/id=a5b62851-8268-4b4d-9074-726b4eb87848?cid=b428b4e8-c8b9-41d5-8a10-b4193c789443

Can you elaborate on it not working on a Player? Do you have a presentation of your own I can look at?

**Comment by donnapep** [comment]
@stulees Yes, I tried using the WebM video that was reported in the issue. The Presentation I used is here - http://rva-test.appspot.com/#/PRESENTATION_MANAGE/id=29261ac6-4a64-42ab-8677-bbcd36c2cd6e?cid=b428b4e8-c8b9-41d5-8a10-b4193c789443.

**Comment by stulees** [comment]
@donnapep The company id in the url of the storage file is not the same as the Rise Vision Test Company. I think that storage file in your presentation is from production.

**Comment by donnapep** [comment]
@stulees You're right, it is. I uploaded it to test Storage and now it works. I'm not sure that this PR actually resolves the issue though. I still see a black screen and the loading spinner when it replays the video.

**Comment by stulees** [comment]
@donnapep There is no longer a flash of black (or what was actually the iframe loading its source and creating a momentary white overlay). The spinner is due to buffering and is a necessary internal feature of JWPlayer. It will possibly only occur the first time the video is ever played. I can communicate this to Alex K.

**Comment by donnapep** [comment]
@stulees I'm still seeing the black flash, but that could be because my Windows machine isn't that powerful. Yes, I imagine she'll have to do the validation of this one. :+1:

**Pull request merged**
