### PR TITLE
Adding support for caching files from 3rd party servers

### PR DESCRIPTION
**Pull request by stulees**
- Updated dependency on widget-common to use latest release
- Added new module `non-storage.js` for now handling fetching file urls via `RiseCache` module from widget-common and be responsible for refresh interval
- Consolidated `video.js` handling of storage and non-storage file events (init, refresh) and removed code now handled by `non-storage.js`
- Added applicable test coverage

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review. There is one test that I struggled with getting to work. It's a test to ensure `onFileRefresh` is called when the refresh interval occurs for non-storage. The issue is with advancing the fake timer clock, it's not advancing. I tried all sorts of variations of when and where to apply `sinon.useFakeTimers()` but none seem to work. The test is commented out, let me know if you see where the problem may be. Thanks

**Comment by donnapep** [comment]
@stulees Can you remove those calls to "non-storage file added" and "non-storage file updated"? We don't want to log those.

**Comment by donnapep** [comment]
@stulees Let's revisit this PR after the logging and messaging stuff is taken care of.

**Comment by stulees** [comment]
@donnapep This branch has been rebased and the last commit revises and fixes tests. 

There are two tests that have been commented out due to a problem in the clock tick not triggering the refresh interval. The last test in `logging-nonstorage.html` and the last test of `non-storage.html`. The refresh interval is now within the new `non-storage.js` module and the instance of it gets created in `setAdditionalParams`. I think the fact that this interval is created within an object created dynamically is causing conflict with the use of sinon useFakeTimers. The only workaround I have is to force the call of `onFileRefresh` instead of ticking the clock. Thoughts?

**Comment by donnapep** [comment]
@stulees The "non-storage file added" and "non-storage file updated" events are still being logged, but we don't need those.

There used to be [this code](https://github.com/Rise-Vision/widget-video/blob/master/src/widget/video.js#L210) in `playerReady` which set `error` to null when the refresh fired. So now when `playerReady` gets called in the test in `logging-nonstorage.html`, this no longer fires the refresh timer and so the error is not cleared. You'll need to figure out how to clear it in order to get that test to pass.

Thx.

**Comment by donnapep** [comment]
@stulees Just to clarify, the problem is not with the test. The code needs to clear the `_error` variable when a refresh occurs. Otherwise, an error will be logged when `done` is called, which is not the correct behaviour.

**Comment by stulees** [comment]
@donnapep Not sure where you're seeing the "non-storage file added" and "non-storage-file updated" events being logged, I removed those. 

I'll look at that behaviour again, thanks for catching that.

**Comment by donnapep** [comment]
@stulees Sorry, you're right. I only reviewed the first commit.

**Comment by stulees** [comment]
@donnapep The behaviour is indeed doing what it's supposed to do. 

The new `non-storage.js` starts the refresh timer which it manages itself, see here - https://github.com/Rise-Vision/widget-video/blob/feature/cache-third-party/src/widget/non-storage.js#L24

Upon the refresh interval, it gets the file and calls `onFileRefresh`, see here - https://github.com/Rise-Vision/widget-video/blob/feature/cache-third-party/src/widget/non-storage.js#L27 

The `onFileRefresh` function is where the `_error` and `_playbackError` flags get reset just as they previously were, see here - https://github.com/Rise-Vision/widget-video/blob/feature/cache-third-party/src/widget/video.js#L134-L136

The issue I see in the test (via some logging in the console) is that the interval never fires when advancing the clock, which if it did, it would execute this code - https://github.com/Rise-Vision/widget-video/blob/feature/cache-third-party/src/widget/non-storage.js#L44

**Comment by stulees** [comment]
@donnapep Please review latest commit. The issue was regarding when `sinon.useFakeTimers()` is applied and restored. The refresh interval for non-storage now gets started before any of the mocha tests are ready to execute. So prior to this fix, sinon wasn't overriding the refresh `setInterval` before it started. 

The fix is to stub `setAdditionalParams` and call `sinon.useFakeTimers()` in the stub function, restore the stub function, can re-call `setAdditionalParams`, allowing the fake timer to be applied to the refresh interval.

In `logging-nonstorage.html`, I had to take this farther by rearranging the order of the tests due to having to explicitly recall `sinon.useFakeTimers()` after the test involving ticking the clock for a refresh interval was passed. This is because I had to remove the `suiteSetup` handler for all of the suites so that the fake timer clock for the refresh interval persisted for its test until passed.

**Comment by donnapep** [comment]
@stulees Now that you mentioned the cause, I have seen this before too. A simpler solution is to just initialize the clock higher up in the head before the `video.js` file is loaded. I think we should try that later since this approach is more involved.

Wondering why the `cb` param is needed on all `file_url` properties now? It never used to be.

**Comment by stulees** [comment]
@donnapep I did try that and nothing initialized. Blank white screen, no tests were run, no code got executed. That's why I did it the way you've seen. 

The `cb` param is needed because a cachebuster is applied by default all the time.

**Comment by donnapep** [comment]
@stulees I'm not sure that a cache buster should be added on initial load. I missed that in the original PR in `widget-common`. If there is no Internet connection when the Presentation starts up, would adding a cache buster not mean that the original image won't be found in the cache?

**Comment by stulees** [comment]
@donnapep The `getFile()` function of `RiseCache` module in widget-common allows for an optional flag to prevent a cachebuster from being applied - https://github.com/Rise-Vision/widget-common/blob/master/src/js/rise-cache.js#L46

I had previously not forced by default to apply a cachebuster but reversed the logic from a comment you made on this PR - https://github.com/Rise-Vision/widget-common/pull/78 *"I'm not sure I get why you would want to make a call to Rise Cache without a cache buster. Is there currently a scenario where this is needed?"*

Do you think the initial `getFile()` call should not contain a cachebuster?

**Comment by donnapep** [comment]
@stulees Well, I guess I can think of a scenario where a cache buster isn't needed after all then. It's also how Storage component works. We shouldn't delay this PR any further though, so I guess something to be aware of for now.

**Comment by donnapep** [comment]
:+1:

**Comment by stulees** [comment]
@donnapep Okay, lets keep this in mind for the next PR we do for Video after this PR gets merged. It's a simple change, but will require some revisions of tests probably.

**Comment by donnapep** [comment]
@stulees FullStory is in this one. And I have no idea why the build took offense to that blank line in `widget.js`.

**Comment by stulees** [comment]
@donnapep :+1:

**Comment by stulees** [comment]
@donnapep Please review last commit, thanks.

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
