### PR TITLE
Fixing play/pause sync issue and updating rise-storage

### PR DESCRIPTION
**Pull request by stulees**
- refactored and fixed handling when the player calls `reset` which occurs when "Resume playing from last position" is unchecked and Viewer tells the Widget to pause
- removed unnecessary `clear` function of player which was only called when `showError` runs
- updated `rise-storage` to account for calling startTimer when there is a storage subscription expired error

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi Please review. Should we be now adding the logic for catching `rise-storage-subscription-error` in the Widget? It currently only catches `rise-storage-subscription-expired`.

**Comment by rodrigopavezi** [comment]
@stulees code looks good. I think we can add handler for it so we log that the error happened. But I don't think we should show a error message as it should continue to play the video fine if the subscription hasn't expired. Thoughts? cheers

**Comment by stulees** [comment]
@rodrigopavezi Agreed, I'll add the handlers now for catching it and logging. Will commit it to this PR.

**Comment by rodrigopavezi** [comment]
@stulees sounds good. cheers

**Comment by stulees** [comment]
@rodrigopavezi Please review last commit, thanks

**Comment by rodrigopavezi** [comment]
@stulees I think we can also log the status of the error. The event has a resp on it.

https://github.com/Rise-Vision/web-component-rise-storage/blob/master/rise-storage.html#L444

What do you think?

cheers

**Comment by stulees** [comment]
@rodrigopavezi I've revised to include the status of the response error in `event_details` when logging. Please review that last commit again, thanks.

**Comment by rodrigopavezi** [comment]
@stulees looks good 👍 cheers

**Pull request merged**
