### PR TITLE
Fix/fixes issue 213 [stage-6]

### PR DESCRIPTION
**Pull request by jungeunyoon**
- on [stage-6]
- example presentation [here](https://apps.risevision.com/editor/workspace/8466eb6a-321b-41df-b467-884c20aa455f/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f)

### CODE REVIEW

**Comment by jungeunyoon** [comment]
[widget-video -- Issue 213 [3]](https://trello.com/c/fhriNHQ7/5324-widget-video-issue-213-3)

**Comment by rudibravo** [comment]
@jungeunyoon you probably want to trigger another build if you are still using stage-6 on your Presentations.
Also do you have a link for the presentation with the staged version? Thanks.

**Comment by jungeunyoon** [comment]
@rudibravo yes realized that 👍 presentation is linked above.

**Comment by jungeunyoon** [comment]
@rudibravo please review.

**Comment by rudibravo** [comment]
@jungeunyoon looks good 👍

**Pull request merged**
