### PR TITLE
Refactor Settings, use JWPlayer, and circumvent memory issues

### PR DESCRIPTION
**Pull request by stulees**

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Due to major refactoring, going to break this out into a few commits to make it easier for you to review. Latest commit addresses:
- bower and npm package dependency updates
- gulpfile removed widget e2e test infrastructure and ensuring default environment is `prod` for a build
- refactor Settings to follow same settings as Video Folder Widget and remove Background Setting
- widget code updated to remove Background 

Please review, thanks

**Comment by donnapep** [comment]
@stulees One comment. Otherwise :+1:

**Comment by stulees** [comment]
@donnapep Whoops, good catch. That was for testing purposes. I'll make sure it's corrected in the next commit, thanks!

**Comment by stulees** [comment]
@donnapep Please review latest commit, thanks.

**Comment by donnapep** [comment]
:+1:

**Comment by stulees** [comment]
@donnapep Please review last two commits, thanks

**Comment by donnapep** [comment]
:+1: Just a general observation in that it's usually better to have a single assertion per test case where it makes sense to do so. Grouping them together makes it difficult to tell which one failed.

**Pull request merged**
