### PR TITLE
Adding test case for fix to non-storage messaging

### PR DESCRIPTION
**Pull request by stulees**
- Added mock for `FrameController` module
- Added non-storage data
- Added non-storage integration test for showing the waiting message and not showing a message when player is ready

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by stulees** [comment]
@donnapep FYI, I'm going to add the additional line to `circle.yml` to produce the `dist.tar.gz` in this PR also, coming in next commit.

**Comment by donnapep** [comment]
:+1: for first commit.

**Comment by stulees** [comment]
@donnapep Please review the last two commits. You can verify the configuration worked by looking at the last build on CCI - https://circleci.com/gh/Rise-Vision/widget-video/139#artifacts

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
