### PR TITLE
Updating rise-storage to include usage logging [stage-2]

### PR DESCRIPTION
**Pull request by stulees**
- Ensuring `usage` is set on rise-storage v2 with value "widget"
- Added integration test

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks

**Comment by donnapep** [comment]
@stulees Is the new Gulp task being added to this PR?

**Comment by stulees** [comment]
@donnapep Thanks for the reminder. Added in last commit.

**Comment by donnapep** [comment]
@stulees Good stuff. Thx! 👍

**Pull request merged**
