### PR TITLE
Rename error logging events [stage-1]

### PR DESCRIPTION
**Pull request by donnapep**
- cache error be renamed to rise cache error
- storage error be renamed to rise storage error

### CODE REVIEW

**Comment by donnapep** [comment]
@rodrigopavezi @stulees Please review. Thx.

**Comment by rodrigopavezi** [comment]
@donnapep looks good. Would make sense if you also make of this card https://trello.com/c/fbaj3GIJ/1073-1-for-rise-storage-error-update-message-in-placeholder-to-there-was-a-problem-communicating-with-rise-storage together with these changes?

**Comment by donnapep** [comment]
@rodrigopavezi Shouldn't they go separately so that we can deploy changes faster?

**Comment by rodrigopavezi** [comment]
@donnapep sure, it can be. cheers

**Comment by donnapep** [comment]
@rodrigopavezi To clarify, do you mean that the cards should be merged, or that this change should be deployed separately? Thx.

**Comment by rodrigopavezi** [comment]
@donnapep they can go separated. Just there is a missing part of the card work in here. More details on the card. I just made a comment there. cheers

**Comment by donnapep** [comment]
@rodrigopavezi Added status code. Please review. Thx.

**Comment by rodrigopavezi** [comment]
@donnapep awesome!! looks good :+1: cheers

**Pull request merged**
