### PR TITLE
Upgrading to include subscription status in file selector

### PR DESCRIPTION
**Pull request by stulees**

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review (last commit in list). This PR won't get merged until it is rebased after PR #70 gets merged. Thanks

**Comment by donnapep** [comment]
:+1:

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review last commit, thanks

**Comment by rodrigopavezi** [comment]
@stulees looks good :+1: cheers

**Pull request merged**
